# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

setup_travis

default_platform(:ios)

platform :ios do
  desc "Runs all the tests"
  lane :tests do
    run_tests(scheme: "MyAppTests")
  end

  desc "Submit a new Beta Build"
  lane :beta do
    build_app
    firebase_app_distribution(
      app: "learning-flutter-d583b",
      groups: "qa-team, trusted-testers"
    )
  end
end
